# Services package - session store, file indexer, event emitter, etc.
from app.services.event_emitter import EventEmitter, EventType, AgentEvent
from app.services.session_store import (
    SessionStore,
    SessionState,
    session_store,
    mark_document_as_read,
    mark_document_in_context,
    is_document_read,
    is_document_in_context,
    cache_search_results,
    get_cached_search,
    remember_entity,
    find_entity,
    get_all_entities,
    set_task_goal,
    add_task,
    update_task_status,
    get_task_plan,
    clear_task_plan,
    get_next_task,
    cache_document_content,
    get_cached_document_content,
)

__all__ = [
    "EventEmitter",
    "EventType",
    "AgentEvent",
    "SessionStore",
    "SessionState", 
    "session_store",
    "mark_document_as_read",
    "mark_document_in_context",
    "is_document_read",
    "is_document_in_context",
    "cache_search_results",
    "get_cached_search",
    "remember_entity",
    "find_entity",
    "get_all_entities",
    "set_task_goal",
    "add_task",
    "update_task_status",
    "get_task_plan",
    "clear_task_plan",
    "get_next_task",
    "cache_document_content",
    "get_cached_document_content",
]
