"""Add available_credits to User

Revision ID: e541f0c4d125
Revises: 7f7f819028c9
Create Date: 2026-01-17 17:14:58.495986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e541f0c4d125'
down_revision: Union[str, None] = '7f7f819028c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('available_credits', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'available_credits')
    # ### end Alembic commands ###
